compile_rm:
	gcc -o rm_external rm_external.c
compile_mk:
	gcc -o mkdir_external mkdir_external.c
compile_ls:
	gcc -o ls_external ls_external.c
compile_cat:
	gcc -o cat_external cat_external.c
compile_date:
	gcc -o date_external date_external.c
compile_shell:
	gcc hello.c
run:
	./a.out
